### ISSUE TITLE
compile failed at openwrt ver14.07

### ISSUE THREAD

**Issue by clough2004** [Akagi201/port-mirroring#1]
error message:
make[4]: Entering directory `/samba/part2/openwrt_14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/port-mirroring-1.3-1'
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
. /samba/part2/openwrt_14.07/openwrt/include/shell.sh; gzip -dc /samba/part2/openwrt_14.07/openwrt/dl/port-mirroring-1.3.tar.gz | /bin/tar -C /samba/part2/openwrt_14.07/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/port-mirroring-1.3-1/.. -xf - 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

can you help to fix it?

**Comment by Akagi201** [comment]
Hi @clough2004

I know it.

You can use origional Makefile. It works.

My modified Makefile. I will check it later. maybe in a week.

**Comment by clough2004** [comment]
@Akagi201
Thanks for your reply.
I have checked the Makefile again and again, and it seems nothing was wrong compared to other package's Makefile .I'm a fresh man to openwrt . This compiling error has bothered me for a couple of days .

**Comment by Akagi201** [comment]
@clough2004 
Yes, it is strange to me ether. Maybe I need to read the makefile which build port-mirroring. I may look into it later. I am playing with python these days.

**Comment by clough2004** [comment]
@Akagi201
I tried to rebuild the compiling environment ,it was spending me  half a night to do so. But it was still failed to pass the compiling process. The error message is different:
make[3]: Entering directory `/home/llh/Openwrt/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/port-mirroring-1.3-1'
Makefile:108: *** DESCRIPTION:= is obsolete, use Package/PKG_NAME/description.  Stop.
make[3]: Leaving directory`/home/llh/Openwrt/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/port-mirroring-1.3-1'
make[2]: **\* [/home/llh/Openwrt/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/port-mirroring-1.3-1/.built] Error 2
make[2]: Leaving directory `/home/llh/Openwrt/openwrt/package/port-mirroring'
make[1]: *** [package/port-mirroring/compile] Error 2
make[1]: Leaving directory`/home/llh/Openwrt/openwrt'
make: **\* [package/port-mirroring/compile] 閿欒 2

**Comment by Akagi201** [comment]
@clough2004 

Sorry for the error.

I modify the file mod and fix it.
